name: Packaging Harmonic Mean
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push
jobs:
  # format:
  #   name: Format
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: format
      
  say-hello:
    name: Say Hello the job
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello the step
        run: echo "Hello!!!"
