name: Packaging Harmonic Mean
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push
jobs:
  format:
    name: Format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install tox
      - name: Run black
        run: tox -e format
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install tox
      - name: Run flake8
        run: tox -e lint
  typecheck:
    name: Typecheck
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install tox
      - name: Run mypy
        run: tox -e typecheck
